import Head from "next/head";
import { useSelector} from "react-redux";
import { RootState} from "../redux/store";
import Pagination from "../components/Pagination";
import UserInputForm from "../components/UserInputForm";
import ProfileUser from "../components/ProfileUser";

export default function Home() {
  const { repos } = useSelector(({ githubRepos }: RootState) => githubRepos);

  return (
    <div>
      <Head>
        <title>My Tens</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <UserInputForm/>
      <ProfileUser/>
      {repos.length > 0 && <Pagination />}
    </div>
  );
}
