import Head from "next/head";
import { useSelector } from "react-redux";
import { RootState } from "../redux/store";
import { Banner, UserInputForm, ProfileUser, Pagination } from "../components";

export default function Home() {
  const { repos, error, profile } = useSelector(
    ({ githubRepos }: RootState) => githubRepos
  );

  return (
    <div>
      <Head>
        <title>My Tens</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex gap-4 justify-center items-center flex-col">
        <Banner />
        <UserInputForm />
        {!error && profile && <ProfileUser />}
        {repos.length > 0 && <Pagination />}
      </main>
    </div>
  );
}
