import Head from "next/head";
import { useSelector, useDispatch } from "react-redux";
import { RootState, AppDispatch, store } from "../redux/store";
import {
  fetchProfileUser,
  fetchRepositories,
} from "../redux/slices/githubReposSlice";
import React, { useEffect, useState, SyntheticEvent, useRef } from "react";

export default function Home() {
  const { profile, repos, isLoading } = useSelector(
    ({ githubRepos }: RootState) => githubRepos
  );
  const dispatch = useDispatch<AppDispatch>();

  const [userInput, setUserInput] = useState("");
  const inputRef = useRef(null);
  useEffect(() => {
    if (userInput) {
      dispatch(fetchProfileUser(userInput) as any);
      dispatch(fetchRepositories(userInput) as any);
    }
  }, [dispatch, userInput]);

  function onSubmit(e: SyntheticEvent) {
    e.preventDefault();
    setUserInput(inputRef.current?.value);
  }

  return (
    <div>
      <Head>
        <title>My Tens</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <form onSubmit={onSubmit}>
        <input
          type="search"
          placeholder="Search user"
          className="border-2 border-black"
          ref={inputRef}
        />
        <button type="submit" className="px-4 py-1 bg-blue-400">
          Submit
        </button>
      </form>
      {repos.map((repo) => (
        <div key={repo.id}>
          <p className="text-xs">{repo.full_name}</p>
        </div>
      ))}

      {isLoading && <p className="text-4xl font-bold">Loading...</p>}
    </div>
  );
}
